apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      containers:
          - name: grafana
            image: grafana/grafana:latest
            ports:
              - containerPort: 3000
            env:
              - name: GF_SECURITY_ADMIN_USER
                value: "admin"
              - name: GF_SECURITY_ADMIN_PASSWORD
                value: "admin"
              - name: GF_USERS_ALLOW_SIGN_UP
                value: "false"
            volumeMounts:
              - name: grafana-datasources
                mountPath: /etc/grafana/provisioning/datasources
              - name: grafana-dashboards
                mountPath: /etc/grafana/provisioning/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards


