replicaCount: 1
image:
  repository: grafana/grafana
  tag: latest
  pullPolicy: IfNotPresent


grafana:
  datasourceFile: "provisioning/datasources/datasource.yml"
  dashboardFilesPath: "provisioning/dashboards/*"
